Repository linhnguyen1411/bachhoason, pull requests merged in 2018-10, with the labels that each got.

#7 test issue
  backend/db/seeds.rb
Labels: reviewing

#9 test issue 2
  backend/db/seeds.rb
Labels: reviewing

#12 test is 3
  backend/db/seeds.rb
Labels: merge, reviewing

#14 revert test issue
  backend/db/seeds.rb
Labels: merge, reviewing

#5 add seed db
  backend/Gemfile
  backend/Gemfile.lock
  backend/app/models/admin.rb
  backend/app/models/paint.rb
  backend/app/models/provider.rb
  backend/app/models/role.rb
  backend/app/services/convert_en_name_service.rb
  backend/db/migrate/20181029034531_devise_create_admins.rb
  backend/db/migrate/20181029064104_create_abouts.rb
  backend/db/migrate/20181029082947_create_roles.rb
  backend/db/schema.rb
  backend/db/seeds.rb
  backend/test/fixtures/roles.yml
  backend/test/models/role_test.rb
Labels: reviewing

#31 change menu
  backend/app/assets/javascripts/admin_manager.js
  backend/app/views/admins/dashboards/index.html.erb
  backend/app/views/layouts/admin_manager.html.erb
  backend/app/views/layouts/admins/_sidebar.html.erb
  backend/config/routes.rb
Labels: reviewing

#38 rename paint to catalog
  backend/app/models/catalog.rb
  backend/config/routes.rb
  backend/db/migrate/20181029064526_create_provider_details.rb
  backend/db/migrate/20181029064537_create_catalogs.rb
  backend/db/migrate/20181029064537_create_paints.rb
  backend/db/schema.rb
  backend/db/seeds.rb
Labels: change something, merge
